apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    pods: "10" # Specifies the maximum number of pods that can be created in the 'dev' namespace.
    requests.cpu: "4" # Specifies the maximum amount of CPU resources that can be requested in the 'dev' namespace.
    requests.memory: "8Gi" # Specifies the maximum amount of memory resources that can be requested in the 'dev' namespace.
    limits.cpu: "8" # Specifies the maximum amount of CPU resources that can be limited in the 'dev' namespace.
    limits.memory: "16Gi" # Specifies the maximum amount of memory resources that can be limited in the 'dev' namespace.





#kubectl create ns dev
#kubectl config set-context --current --namespace=dev
#kubectl config view

