apiVersion: v1
kind: pod
metadata:
  name: sidecar-pod_log_aggregator
spec:
  containers:
  - name: main-app-container
    image: alphine:latest
    command: ["/bin/sh", "-c", "while true; do date >> /var/log/app.log; sleep 10; done"] # Specifies a command that runs in the main application container, which appends the current date to a log file every 10 seconds. This simulates log generation for demonstration purposes.
    volumeMounts:
    - name: shared-log
      mountPath: /var/log # Specifies the path inside the main application container where the shared volume will be mounted.  
  - name: sidecar-container
    image: nginx:latest
    volumeMounts:
    - name: shared-log
      mountPath: /usr/share/nginx/html # Specifies the path inside the sidecar container where the shared volume will be mounted.
  volumes:
  - name: shared-log # Specifies the name of the volume, which should match the name used in the volumeMounts section of both containers.
    emptyDir: {} # Specifies that the volume is an empty directory, which will be created when the pod is assigned to a node and will exist as long as the pod is running. This allows both containers to share data through this volume.


#kubectl create -f sidecar.yml
#kubectl get pods -->here we can see one pod two containers
#kubectl describe pods 
#kubectl exec -it sidecar-pod_log_aggregator -c sidecar-container -- /bin/bash  --->loginto to sidecar contianer
#ls -l /usr/share/nginx/html  --here we can see app.log file data
